/* 图片采集器：DOM + 懒加载 + srcset + CSS + Resource Timing + 动态页面。视频/音频由 MediaCollector 负责。 */
import { CONFIG } from "../config.js";
import { Utils } from "../utils/index.js";
import { BlobManager } from "../services/BlobManager.js";
import { Deduplication } from "./Deduplication.js";
class ImageCollectorService{
 constructor(){this.observer=null;this.po=null;this.lazyAttrs=['data-src','data-original','data-lazy-src','data-srcset','data-url','data-echo','data-lazy','data-full','data-real-src','data-bg','data-bg-url','data-image','data-img','data-load','data-lazyload','data-original-src','data-highres','data-normal','data-small','data-medium','data-large','data-fallback','data-zoom','data-full-src','data-original-url','data-poster'];}
 _ui(e){return!!(e&&e.closest&&e.closest('#_hy-root'))}
 _norm(u){if(!u||typeof u!=='string')return'';let s=u.trim();if(!s||s==='#'||s.startsWith('data:')||s.startsWith('javascript:'))return'';s=s.replace(/^url\(\s*["']?/i,'').replace(/["']?\s*\)$/,'');try{return new URL(s,location.href).href}catch(_){return''}}
 _ext(u){try{const x=new URL(u,location.href),a=[x.pathname,x.searchParams.get('filename')||'',x.searchParams.get('file')||'',x.searchParams.get('name')||''];for(const s of a){const m=String(s).match(/\.([a-z0-9]{1,10})(?:$|[?#])/i);if(m)return m[1].toLowerCase()}}catch(_){}return''}
 _isImage(u,mime='',hint=''){const m=String(mime).toLowerCase();if(m.startsWith('image/'))return true;const e=this._ext(u);if(['jpg','jpeg','png','gif','bmp','webp','avif','svg','svgz','ico','tif','tiff','jxl','heic','heif'].includes(e))return true;const s=(String(u)+' '+hint).toLowerCase();return/(?:^|[/?_-])(image|img|photo|picture|thumbnail|thumb)(?:[/?_-]|$)/.test(s)}
 _name(u,alt){if(alt&&String(alt).trim())return String(alt).trim();try{const x=new URL(u,location.href),q=x.searchParams.get('filename')||x.searchParams.get('file')||x.searchParams.get('name');if(q)return decodeURIComponent(q).replace(/\.[^.]+$/,'');const p=x.pathname.split('/').filter(Boolean).pop();return p?decodeURIComponent(p).replace(/\.[^.]+$/,''):'图片'}catch(_){return'图片'}}
 _push(items,seen,u,el=null,source='dom',mime=''){const full=this._norm(u);if(!full||seen.has(full)||!this._isImage(full,mime,source))return;seen.add(full);const ext=this._ext(full)||(String(mime).match(/image\/([a-z0-9.+-]+)/i)?.[1]||CONFIG.image.defaultImageFormat);const name=this._name(full,el?.alt);items.push({id:Utils.generateUniqueId(),url:full,preview:full,name:Utils.truncateTo4Bytes(name),originalName:name,originalFormat:ext,format:Utils.truncateTo4Bytes(ext),mediaType:'image',type:source,width:el?.naturalWidth||el?.width||'未知',height:el?.naturalHeight||el?.height||'未知',fileSize:'未知',mime:mime||'',source,svgContent:''})}
 _srcset(v){return String(v||'').split(',').map(x=>x.trim().split(/\s+/)[0]).filter(Boolean)}
 _scan(items,seen){const addAttrs=el=>this.lazyAttrs.forEach(a=>{const v=el.getAttribute?.(a);if(!v)return;a.includes('srcset')?this._srcset(v).forEach(u=>this._push(items,seen,u,el,'lazy-srcset')):this._push(items,seen,v,el,'lazy-attr')});document.querySelectorAll('img,picture source').forEach(el=>{if(this._ui(el))return;if(el.currentSrc||el.src)this._push(items,seen,el.currentSrc||el.src,el,'element');if(el.srcset)this._srcset(el.srcset).forEach(u=>this._push(items,seen,u,el,'srcset'));addAttrs(el)});const selector=this.lazyAttrs.map(a=>`[${a}]`).join(',');if(selector)document.querySelectorAll(selector).forEach(el=>{if(!this._ui(el))addAttrs(el)});document.querySelectorAll('link[rel="preload"][as="image"],link[rel="prefetch"][as="image"],link[rel*="icon"]').forEach(el=>{if(el.href)this._push(items,seen,el.href,el,'preload')});document.querySelectorAll('meta[property^="og:image"],meta[name="twitter:image"]').forEach(el=>this._push(items,seen,el.content,el,'meta'));document.querySelectorAll('svg').forEach(svg=>{if(this._ui(svg)||svg.closest('img'))return;try{const content=svg.outerHTML;if(content.length<20)return;const url=BlobManager.createManagedBlobUrl(new Blob([content],{type:'image/svg+xml'}));this._push(items,seen,url,svg,'SVG标签','image/svg+xml');const x=items[items.length-1];if(x){x.svgContent=content;x.preview=url;x.originalFormat='svg';x.format='svg'}}catch(_){}});document.querySelectorAll('[style*="background"],[style*="background-image"]').forEach(el=>{if(this._ui(el))return;const bg=getComputedStyle(el).backgroundImage;const re=/url\(\s*["']?([^"')]+)["']?\s*\)/gi;let m;while((m=re.exec(bg||'')))this._push(items,seen,m[1],el,'background')})}
 _network(items,seen){try{performance.getEntriesByType('resource').forEach(e=>{if(this._isImage(e.name,'',e.initiatorType))this._push(items,seen,e.name,null,'network')})}catch(_){} }
 startLiveObserver(){if(this.observer||!document.documentElement)return;try{let timer=null;this.observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>this._scanIncremental(),220)});this.observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['src','srcset','style',...this.lazyAttrs]})}catch(_){} }
 _scanIncremental(){try{const items=[],seen=new Set();this._scan(items,seen);this._network(items,seen)}catch(_){} }
 async collectAllImages(signatureMap){this.startLiveObserver();const items=[],seen=new Set();this._scan(items,seen);this._network(items,seen);return Deduplication.checkAndRemoveDuplicates(items,signatureMap)}
 destroy(){try{this.observer?.disconnect();this.po?.disconnect()}catch(_){}this.observer=null;this.po=null}
 static getFileExtension(u){try{return new URL(u,location.href).pathname.match(/\.([a-z0-9]{1,10})$/i)?.[1]||''}catch(_){return''}}
 static truncateTo4Bytes(s,max=CONFIG.image.infoTruncateLength){if(!s)return'';let r='',n=0;for(const ch of String(s)){const b=ch.codePointAt(0)<=0x7f?1:ch.codePointAt(0)<=0x7ff?2:3;if(n+b>max)return r+'...';r+=ch;n+=b}return r}
 static getImageName(u,alt){return alt||this._nameFallback(u)}
 static _nameFallback(u){try{return decodeURIComponent(new URL(u,location.href).pathname.split('/').filter(Boolean).pop()||'未命名图片').replace(/\.[^.]+$/,'')}catch(_){return'未命名图片'}}
}
export const ImageCollector=new ImageCollectorService();
