/** 多媒体资源采集器：DOM + Resource Timing + fetch/XHR + HLS/DASH。 */
import { Utils } from "../utils/index.js";
class MediaCollectorService {
 constructor(){this.items=new Map();this.installed=false;this.manifestSeen=new Set();this.pendingNotify=null;this.onResource=null;this.mime=new Map([['video/mp4','video'],['video/webm','video'],['video/ogg','video'],['video/quicktime','video'],['video/x-m4v','video'],['video/x-msvideo','video'],['video/mpeg','video'],['video/mp2t','video'],['audio/mpeg','audio'],['audio/mp3','audio'],['audio/mp4','audio'],['audio/aac','audio'],['audio/ogg','audio'],['audio/wav','audio'],['audio/x-wav','audio'],['audio/flac','audio'],['audio/webm','audio'],['application/vnd.apple.mpegurl','video'],['application/x-mpegurl','video'],['application/dash+xml','video']]);}
 init(onResource){if(this.installed)return;this.installed=true;this.onResource=onResource;this._scanDom();this._installPerformanceObserver();this._hookFetch();this._hookXHR();document.addEventListener('loadedmetadata',e=>this._mediaElement(e.target),true);document.addEventListener('play',e=>this._mediaElement(e.target),true);document.addEventListener('canplay',e=>this._mediaElement(e.target),true);document.addEventListener('loadstart',e=>this._mediaElement(e.target),true);try{new MutationObserver(()=>this._scheduleScan()).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['src','srcset','poster','preload','data-src','data-srcset','data-url','data-video','data-video-src','data-audio','data-audio-src','data-media','data-file']})}catch(_){}this._timer=setInterval(()=>this._scanPerformance(),2000)}
 _scheduleScan(){clearTimeout(this.pendingNotify);this.pendingNotify=setTimeout(()=>this._scanDom(),160)}
 _normalize(u){try{return u?new URL(String(u),location.href).href:''}catch(_){return''}}
 _scanDom(){try{document.querySelectorAll('video,audio,video source,audio source').forEach(el=>{const tag=el.tagName.toLowerCase(),t=tag==='audio'||el.closest('audio')?'audio':'video';['src','data-src','data-url','data-video','data-video-src','data-audio','data-audio-src','data-media','data-file','data-download'].forEach(a=>{const u=el.getAttribute(a);if(u)this._add(u,null,t,'dom')});if(el.currentSrc)this._add(el.currentSrc,null,t,'dom-current');if(el.src)this._add(el.src,null,t,'dom')});document.querySelectorAll('video[poster]').forEach(v=>this._add(v.poster,'image/*','image','poster'));document.querySelectorAll('link[rel="preload"],link[rel="prefetch"]').forEach(l=>{const a=(l.getAttribute('as')||'').toLowerCase();if(a==='video'||a==='audio')this._add(l.href,null,a,'preload')});}catch(_){}
 }
 _installPerformanceObserver(){try{performance.getEntriesByType('resource').forEach(e=>this._performanceEntry(e));const po=new PerformanceObserver(l=>l.getEntries().forEach(e=>this._performanceEntry(e)));po.observe({type:'resource',buffered:true});this._po=po}catch(_){try{const po=new PerformanceObserver(l=>l.getEntries().forEach(e=>this._performanceEntry(e)));po.observe({entryTypes:['resource']});this._po=po}catch(_){}}}
 _scanPerformance(){try{performance.getEntriesByType('resource').forEach(e=>this._performanceEntry(e))}catch(_){}
 }
 _performanceEntry(e){if(!e||!e.name||/^blob:|^data:/i.test(e.name))return;const i=String(e.initiatorType||'').toLowerCase();const t=(i==='video'||i==='audio'||i==='media')?(i==='audio'?'audio':'video'):this._guessType(e.name);if(t)this._add(e.name,null,t,'performance')}
 _hookFetch(){const original=window.fetch;if(typeof original!=='function'||original.__rsMediaWrapped)return;const self=this;const wrapped=function(){let u='';try{const x=arguments[0];u=typeof x==='string'?x:x?.url||''}catch(_){}return original.apply(this,arguments).then(r=>{try{const full=self._normalize(r.url||u),ct=r.headers.get('content-type')||'',t=self._mimeType(ct)||self._guessType(full);if(t){self._add(full,ct,t,'fetch');if(t==='video'&&self._isManifest(ct,full))self._parseManifestResponse(r.clone(),full)}}catch(_){}return r})};wrapped.__rsMediaWrapped=true;try{window.fetch=wrapped}catch(_){}
 }
 _hookXHR(){const open=XMLHttpRequest.prototype.open,send=XMLHttpRequest.prototype.send;if(open.__rsMediaWrapped)return;const self=this;XMLHttpRequest.prototype.open=function(m,u){this.__rsMediaUrl=u;return open.apply(this,arguments)};XMLHttpRequest.prototype.send=function(){this.addEventListener('loadend',function(){try{const full=self._normalize(this.responseURL||this.__rsMediaUrl),ct=this.getResponseHeader('content-type')||'',t=self._mimeType(ct)||self._guessType(full);if(t){self._add(full,ct,t,'xhr');if(t==='video'&&self._isManifest(ct,full)&&typeof this.responseText==='string')self._parseManifestText(this.responseText,full)}}catch(_){}},{once:true});return send.apply(this,arguments)};try{XMLHttpRequest.prototype.open.__rsMediaWrapped=true}catch(_){}
 }
 async _parseManifestResponse(r,u){try{this._parseManifestText(await r.text(),u)}catch(_){}
 }
 _parseManifestText(text,base){if(!text||this.manifestSeen.has(base))return;this.manifestSeen.add(base);const h=/#EXTM3U|#EXT-X-STREAM-INF|#EXTINF/i.test(text),d=/<MPD[\s>]/i.test(text);if(!h&&!d)return;if(h)text.split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!x.startsWith('#')).forEach(x=>{try{this._add(new URL(x,base).href,null,'video','hls')}catch(_){}});if(d){const re=/<BaseURL[^>]*>([^<]+)<\/BaseURL>|(?:media|initialization)\s*=\s*["']([^"']+)["']/gi;let m;while((m=re.exec(text))){try{this._add(new URL(m[1]||m[2],base).href,null,'video','dash')}catch(_){} }}}
 _isManifest(ct,u){return /mpegurl|dash\+xml/i.test(ct||'')||/\.(m3u8|mpd)(?:[?#]|$)/i.test(u)}
 _mimeType(ct){const k=String(ct||'').split(';')[0].trim().toLowerCase();return this.mime.get(k)||(k.startsWith('video/')?'video':k.startsWith('audio/')?'audio':'')}
 _guessType(u){const s=String(u||'');if(/\.(mp4|webm|mkv|mov|m4v|avi|flv|ts|m3u8|mpd|mpeg|mpg|m2ts)(?:[?#]|$)/i.test(s)||/videoplayback|video|stream/i.test(s))return'video';if(/\.(mp3|m4a|aac|ogg|opus|wav|flac|wma|aiff)(?:[?#]|$)/i.test(s)||/audio|music|sound/i.test(s))return'audio';return''}
 _mediaElement(el){if(!el||!['VIDEO','AUDIO'].includes(el.tagName))return;const t=el.tagName==='AUDIO'?'audio':'video';if(el.currentSrc)this._add(el.currentSrc,null,t,'element');if(el.src)this._add(el.src,null,t,'element');el.querySelectorAll('source').forEach(s=>{if(s.src)this._add(s.src,null,t,'element')})}
 _add(url,mime,type,source){if(!url||!type||type==='image')return;const full=this._normalize(url);if(!full||/^blob:|^data:/i.test(full))return;const key=`${type}|${full}`;if(this.items.has(key))return;const ext=this._extension(full,mime,type),base=this._name(full,type),item={id:Utils.generateUniqueId(),url:full,preview:full,originalName:base,name:base,originalFormat:ext,format:ext||type,originalType:source||type,type:type==='video'?'视频':'音频',mediaType:type,width:'媒体',height:'媒体',fileSize:'未知',mime:mime||'',source};this.items.set(key,item);if(this.onResource)this.onResource(item)}
 _extension(u,mime,type){const m=String(mime||'').match(/(?:video|audio)\/([a-z0-9.+-]+)/i);if(m){let x=m[1].toLowerCase();if(x==='mpeg')x=type==='audio'?'mp3':'mpeg';if(x==='x-m4a')x='m4a';return x}const q=String(u).match(/\.([a-z0-9]{1,8})(?:[?#]|$)/i);return q?q[1].toLowerCase():(/m3u8/i.test(u)?'m3u8':/mpd/i.test(u)?'mpd':type)}
 _name(u,type){try{const p=new URL(u).pathname.split('/').filter(Boolean).pop();return(p||`${type}-${Date.now()}`).replace(/\.[^.]+$/,'')||`${type}-${Date.now()}`}catch(_){return`${type}-${Date.now()}`}}
 destroy(){clearInterval(this._timer);clearTimeout(this.pendingNotify);try{this._po?.disconnect()}catch(_){}this._po=null}
}
export const MediaCollector=new MediaCollectorService();
